src/Entity/Event.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Persistence\ManagerRegistry;
use App\Entity\BarsEvent;

/**
 * Event
 *
 * @ORM\Table(name="Event", uniqueConstraints={@ORM\UniqueConstraint(name="Event_ID_uindex", columns={"ID"})}, indexes={@ORM\Index(name="Event_File_image_event_fk", columns={"fk_image_affiche"}), @ORM\Index(name="Event_Bar_ID_fk", columns={"fk_bar_id"})})
 * @ORM\Entity
 */
class Event
{
    /**
     * @var int
     *
     * @ORM\Column(name="ID", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $ID;

    /**
     * @var string
     *
     * @ORM\Column(name="event_name", type="string", length=255, nullable=false)
     */
    private $eventName;

    /**
     * @var int
     *
     * @ORM\Column(name="publication_date", type="integer", nullable=false)
     */
    private $publicationDate;

    /**
     * @var int
     *
     * @ORM\Column(name="event_date", type="integer", nullable=false)
     */
    private $eventDate;

    /**
     * @var string|null
     *
     * @ORM\Column(name="information", type="string", length=255, nullable=true)
     */
    private $information;

    /**
     * @var bool|null
     *
     * @ORM\Column(name="is_active", type="boolean", nullable=true, options={"default"="1"})
     */
    private $isActive = '1';

    /**
     * @var File
     *
     * @ORM\ManyToOne(targetEntity="File")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="fk_image_affiche", referencedColumnName="ID")
     * })
     */
    private $fkImageAffiche;

    /**
     * @var int
     * @ORM\Column(name="fk_bar_id", type="integer", nullable=true)
     */
    private $fkBar;

    public function getID(): ?int
    {
        return $this->ID;
    }

    public function getEventName(): ?string
    {
        return $this->eventName;
    }

    public function setEventName(string $eventName): self
    {
        $this->eventName = $eventName;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        $date = date('Y-m-d H:i:s', ($this->publicationDate));
        try {
            return new \DateTime($date);
        } catch (\Exception $e) {
            echo $e->getMessage();
        }
    }

    public function setPublicationDate(): self
    {
        $this->publicationDate = time();

        return $this;
    }

    public function getEventDate(): ?\DateTimeInterface
    {
        $date = date('Y-m-d H:i:s', ($this->eventDate));
        try {
            return new \DateTime($date);
        } catch (\Exception $e) {
            echo $e->getMessage();
        }
    }

    public function setEventDate(\DateTime $date): self
    {
        $this->eventDate = $date->getTimestamp();;

        return $this;
    }

    public function getInformation(): ?string
    {
        return $this->information;
    }

    public function setInformation(?string $information): self
    {
        $this->information = $information;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(?bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getFkImageAffiche(): ?File
    {
        return $this->fkImageAffiche;
    }

    public function getAfficheFilepath(): ?string
    {
        if ($this->fkImageAffiche)
            return $this->fkImageAffiche->getFilepath();
        return null;
    }

    public function setFkImageAffiche(?File $fkImageAffiche): self
    {
        $this->fkImageAffiche = $fkImageAffiche;

        return $this;
    }

    public function getFkBar(): ?int
    {
        return $this->fkBar;
    }

    public function setFkBar(?int $id): self
    {
        $this->fkBar = $id;
        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * User
 *
 * @ORM\Table(name="User", uniqueConstraints={@ORM\UniqueConstraint(name="User_ID_uindex", columns={"ID"})}, indexes={@ORM\Index(name="User_File_ID_fk", columns={"fk_profil_picture"}), @ORM\Index(name="User_Account_type_ID_fk", columns={"fk_account_type_id"})})
 * @ORM\Entity
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="ID", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=255, nullable=false)
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="last_name", type="string", length=255, nullable=false)
     */
    private $lastName;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255, nullable=false)
     */
    private $email;

    /**
     * @var string|null
     *
     * @ORM\Column(name="pass", type="string", length=255, nullable=true)
     */
    private $pass;

    /**
     * @var int|null
     *
     * @ORM\Column(name="birth_date", type="integer", nullable=true)
     */
    private $birthDate;

    /**
     * @var int|null
     *
     * @ORM\Column(name="signup_date", type="integer", nullable=true)
     */
    private $signupDate;

    /**
     * @var int|null
     *
     * @ORM\Column(name="last_login", type="integer", nullable=true)
     */
    private $lastLogin;

    /**
     * @var bool
     *
     * @ORM\Column(name="is_active", type="boolean", nullable=false, options={"default"="1"})
     */
    private $isActive = '1';

    /**
     * @var File
     *
     * @ORM\ManyToOne(targetEntity="File")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="fk_profil_picture", referencedColumnName="ID")
     * })
     */
    private $fkProfilPicture;

    /**
     * @var AccountType
     *
     * @ORM\ManyToOne(targetEntity="AccountType")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="fk_account_type_id", referencedColumnName="ID")
     * })
     */
    private $fkAccountType;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->email;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->pass;
    }

    public function setPass(?string $pass): self
    {
        $this->pass = $pass;

        return $this;
    }

    public function getBirthDate(): ?int
    {
        return $this->birthDate;
    }

    public function setBirthDate(?int $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getSignupDate(): ?int
    {
        return $this->signupDate;
    }

    public function setSignupDate(?int $signupDate): self
    {
        $this->signupDate = $signupDate;

        return $this;
    }

    public function getLastLogin(): ?int
    {
        return $this->lastLogin;
    }

    public function setLastLogin(?int $lastLogin): self
    {
        $this->lastLogin = $lastLogin;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getFkProfilPicture(): ?File
    {
        return $this->fkProfilPicture;
    }

    public function setFkProfilPicture(?File $fkProfilPicture): self
    {
        $this->fkProfilPicture = $fkProfilPicture;

        return $this;
    }

    public function getFkAccountType(): ?AccountType
    {
        return $this->fkAccountType;
    }

    public function setFkAccountType(?AccountType $fkAccountType): self
    {
        $this->fkAccountType = $fkAccountType;

        return $this;
    }

    public function setAll(User $user)
    {
        $this->firstName = $user->firstName;
        $this->lastName = $user->lastName;
        $this->email = $user->email;
        $this->birthDate = $user->birthDate;
        $this->fkProfilPicture = $user->fkProfilPicture;

    }


    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        return array($this->getFkAccountType()->getRoleName(),);
    }

    /**
     * @inheritDoc
     */
    public function getSalt()
    {
        // we don't do it here
        return null;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Bar;
use App\Entity\Event;
use App\Entity\File;
use App\Form\EventType;
use Doctrine\Bundle\DoctrineBundle\Registry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @Route("/event")
 */
class EventController extends AbstractController
{
    /**
     * @Route("/", name="event_index", methods={"GET"})
     */
    public function index(): Response
    {
        $events = $this->getDoctrine()
            ->getRepository(Event::class)
            ->findAll();

        if($this->getUser()){
            if(!array_intersect($this->getUser()->getRoles(), ["admin"])){
                return $this->redirectToRoute("Index");
            }
        }

        /////////////////////// GESTION DROITS /////////////////////
        if($this->getUser()){
            if(!array_intersect($this->getUser()->getRoles(), ["admin"])){
                return $this->redirectToRoute("Index");
            }
        }
        else{
            return $this->redirectToRoute("Index");
        }
        //////////////////////////////////////////////////////////

        return $this->render('event/index.html.twig', [
            'events' => $events,
        ]);
    }

    /**
     * @Route("/bar/{id}", name="events_by_bar", methods={"GET"})
     */
    public function events_by_bar(int $id): Response
    {
        $events = $this->getDoctrine()
            ->getRepository(Event::class)
            ->findByFkBar($id);

        $bar = $this->getDoctrine()
            ->getRepository(Bar::class)
            ->Find($id);

        if($this->getUser()){
            if(!array_intersect($this->getUser()->getRoles(), ["admin", "Owner"]) || !($this->getUser()->getId() == $bar->getFkOwner()->getFkIdUser()->getId()) ){
                return $this->redirectToRoute("Index");
            }
        }
        else{
            return $this->redirectToRoute("Index");
        }

        return $this->render('event/index_by_bar.html.twig', [
            'events' => $events,
            'bar' => $bar
        ]);
    }

    /**
     * @Route("/{id}/new", name="event_new", methods={"GET","POST"})
     */
    public function new(Request $request, int $id): Response
    {

        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $bar = $this->getDoctrine()->getRepository(Bar::class)->find($id);

            $event->setFkBar($bar->getID());
            $event->setPublicationDate();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event_index');
        }

        /////////////////////// GESTION DROITS /////////////////////
        $bar = $this->getDoctrine()
            ->getRepository(Bar::class)
            ->Find($id);

        if(!$bar) return $this->redirectToRoute("Index");

        if($this->getUser()){
            if(!array_intersect($this->getUser()->getRoles(), ["admin", "Owner"]) || !($this->getUser()->getId() == $bar->getFkOwner()->getFkIdUser()->getId()) ){
                return $this->redirectToRoute("Index");
            }
        }
        else{
            return $this->redirectToRoute("Index");
        }
        //////////////////////////////////////////////////////////


        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
            'bar_id' => $id,
        ]);
    }

    /**
     * @Route("/{id}", name="event_show", methods={"GET"})
     */
    public function show(Event $event, int $id): Response
    {
        if($event->getFkImageAffiche())
            $affiche = $this->getDoctrine()
                ->getRepository(File::class)
                ->find($event->getFkImageAffiche())
                ->getFilepath();
        else
            $affiche = null;
        return $this->render('event/show.html.twig', [
            'event' => $event,
            'affichePath' => $affiche
        ]);
    }

    /**
     * @Route("/{id}/edit", name="event_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Event $event, int $id): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $logo = $form->get('fkImageAffiche')->getData();
            $fkLogo = new File();

            if($logo) {

                $originalFilename = pathinfo($logo->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $logo->guessExtension();

                try {
                    $logo->move(
                        $this->getParameter('picturesDirectory'),
                        $newFilename
                    );

                    // on rajoute le fichier en base
                    $fkLogo->setFilepath($newFilename);
                    $fkLogo->setFiletype("affiche");

                    $fileManager = $this->getDoctrine()->getManagerForClass(File::class);
                    $fileManager->persist($fkLogo);
                    $fileManager->flush();

                    $event->setFkImageAffiche($fkLogo);
                } catch (FileException $e) {
                    error_log("=====================" . $e->getMessage() . "================");
                }
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('event_index');
        }

        /////////////////////// GESTION DROITS /////////////////////
        $bar = $this->getDoctrine()
            ->getRepository(Bar::class)
            ->Find($id);

        if(!$bar) return $this->redirectToRoute("Index");

        if($this->getUser()){
            if(!array_intersect($this->getUser()->getRoles(), ["admin", "Owner"]) || !($this->getUser()->getId() == $bar->getFkOwner()->getFkIdUser()->getId()) ){
                return $this->redirectToRoute("Index");
            }
        }
        else{
            return $this->redirectToRoute("Index");
        }
        //////////////////////////////////////////////////////////

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="event_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Event $event): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getID(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('event_index');
    }

    /**
     * @Route("/bar/{id}", name="show_bar_event", methods={"GET"})
     * @return Event[]
     */

    public function showBarsEvents(Event $event)
    {
        return $this->getDoctrine()->getRepository(Event::class)->findBy(array('id' => $this->getParameter("id")));
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn red">
        Supprimer
        <i class="material-icons right">delete</i>
    </button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
<div class="row">
    <div class="input-field col s12 l4">
        {{ form_widget(form.eventName, {'attr': {'class': 'validate','placeholder' : "Nom de l'évènement"}}) }}
        {{ form_label(form.eventName) }}
    </div>
</div>
<div class="row">
    <div class="input-field col s12 l4">
        {{ form_widget(form.eventDate) }}
        <input type="text" class="datepicker">
    </div>
    <div class="input-field col s12 l4">
        <input type="text" class="timepicker">
    </div>
    <script>
        $(document).ready(function () {
            var dateNow = new Date();
            $('.datepicker').val('{{ form.vars.value.eventDate | date("l j F Y")}}');
            $('.timepicker').val('{{ form.vars.value.eventDate | date("H:i")}}');
            $('.datepicker').datepicker({
                'onSelect': function (el) {
                    $('.is-selected').addClass("purple");
                },
                'minDate': dateNow,
                'setDefaultDate': true,
                'defaultDate': dateNow,
                'onClose': function () {
                    month = this.date.getMonth() + 1;
                    day = this.date.getDate();
                    year = this.date.getFullYear();
                    console.log(day + ' ' + month + ' ' + year);
                    // select the good month in the select
                    $("#event_eventDate_date_month,#event_eventDate_date_day,#event_eventDate_date_year").children().each(function () {
                        $(this).removeAttr('selected')
                    });
                    $("#event_eventDate_date_month option[value=" + month + "]").attr('selected', 'selected');
                    $("#event_eventDate_date_day option[value=" + day + "]").attr('selected', 'selected');
                    $("#event_eventDate_date_year option[value=" + year + "]").attr('selected', 'selected');
                },
                'format': 'dddd d mmmm yyyy',
            });
            $('.timepicker').timepicker({
                'twelveHour': false,
                'vibrate': true,
                'onCloseEnd': function () {
                    // select the good month in the select
                    $("#event_eventDate_time_hour,#event_eventDate_time_minute").children().each(function () {
                        $(this).removeAttr('selected')
                    });
                    $("#event_eventDate_time_hour option[value=" + this.hours + "]").attr('selected', 'selected');
                    $("#event_eventDate_time_minute option[value=" + this.minutes + "]").attr('selected', 'selected');
                },
            });

            $('.datepicker-date-display').addClass("purple");
            $('.datepicker-cancel').addClass("purple-text");
            $('.datepicker-done').addClass("purple-text");
            $('.timepicker-digital-display').addClass("purple");
            $('.timepicker-close').addClass("purple-text");
        });
    </script>
</div>
<div class="row">
    <div class="input-field col s12">
        {{ form_widget(form.information) }}
        {{ form_label(form.information) }}
    </div>
</div>
<div class="row">
    <div class="input-field col s12 m8 l6">
        <div class="file-field input-field">
            <div class="btn purple">
                <span>{{ form_label(form.fkImageAffiche, "Photo de profil") }}</span>
                {{ form_widget(form.fkImageAffiche, {'attr': {'class': 'validate'}}) }}
            </div>
            <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="input-field col s12">
        <button class="btn">{{ button_label|default('Save') }}</button>
    </div>
</div>
{{ form_widget(form._token) }}
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends "layout.html.twig" %}

{% block title %}Modification d'un évènement{% endblock %}

{% block body %}
<div class="container">
    <div class="card">
        <div class="card-content">
            <div class="card-title">
                {{ include('event/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
                <div class="card-action">
                    <div class="row">
                        <div class="col s12 m4 center">
                            <a href="{{ path('event_index') }}">
                                <button class="btn grey">
                                    Annuler
                                    <i class="material-icons left">arrow_back</i>
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

templates/event/index.html.twig
{% extends "layout.html.twig" %}

{% block body %}
    <div class="container">
        <div class="card">
            <div class="card-content">
                <table class="table striped responsive-table centered">
                    <thead>
                    <tr>
                        <th>Nom</th>
                        <th><i class="material-icons">event</i></th>
                        <th><i class="material-icons">access_time</i></th>
                        <th>Description</th>
                        <th>Date de publication</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for event in events %}
                        <tr>
                            <td>{{ event.eventName }}</td>
                            <td>{{ event.eventDate|date('d/m/Y') }}</td>
                            <td>{{ event.eventDate|date('H:i') }}</td>
                            <td>{{ event.information|slice(0,30) }}...</td>
                            <td>{{ event.publicationDate|date('H:i d/m/Y') }}</td>
                            <td>
                                <a href="{{ path('event_show', {'id': event.id}) }}"><i class="material-icons">visibility</i></a>
                                <a href="{{ path('event_edit', {'id': event.id}) }}"><i class="material-icons orange-text">edit</i></a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="7">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {#<a href="{{ path('event_new', {"id" : event.fkBar } ) }}">Create new</a>#}
{% endblock %}

templates/event/index_by_bar.html.twig
{% extends "layout.html.twig" %}

{% block body %}
    <div class="container">
        <div class="card">
            <div class="card-content">
                <div class="card-title center">Évènements pour <a href="{{ path('bar_show', {'id': bar.iD}) }}">{{ bar.tradename }}</a></div>
                <table class="table striped responsive-table centered">
                    <thead>
                    <tr>
                        <th>Nom</th>
                        <th><i class="material-icons">event</i></th>
                        <th><i class="material-icons">access_time</i></th>
                        <th>Description</th>
                        <th>Date de publication</th>
                        <th>actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for event in events %}
                        <tr>
                            <td>{{ event.eventName }}</td>
                            <td>{{ event.eventDate|date('d/m/Y') }}</td>
                            <td>{{ event.eventDate|date('H:i') }}</td>
                            <td>{{ event.information|slice(0,30) }}...</td>
                            <td>{{ event.publicationDate|date('H:i d/m/Y') }}</td>
                            <td>


                                <a href="{{ path('event_show', {'id': event.id}) }}"><i class="material-icons">visibility</i></a>
                                <a href="{{ path('event_edit', {'id': event.id}) }}"><i class="material-icons orange-text">edit</i></a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="7">Pas d'évènements enregistrés</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-action center">
                <a class="purple-text" href="{{ path('event_new',{'id' : bar.iD}) }}">Créer un évènement 🎉</a>
            </div>
        </div>
    </div>

    <a href="{{ path('event_new', {'id' : bar.iD}) }}">Create new</a>
{% endblock %}

templates/event/new.html.twig
{% extends "layout.html.twig" %}

{% block title %}Création d'un évènement{% endblock %}

{% block body %}
    <div class="container">
        <div class="card">
            <div class="card-content">
                <div class="card-title">
                    {{ include('event/_form.html.twig', {'button_label': 'Créer'}) }}
                    <div class="card-action">
                        <div class="row">
                            <div class="col s12 m4 center">
                                <a href="{{ path('events_by_bar', {'id': bar_id}) }}">
                                    <button class="btn grey">
                                        Annuler
                                        <i class="material-icons left">arrow_back</i>
                                    </button>
                                </a>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/event/show.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
    <div class="container">
        <div class="card">
            <div class="card-content">
                <div class="card-title">
                    {{ event.eventName }} <span class="purple-text">{{ event.eventDate|date('H:i') }}</span>
                </div>
                <div class="right-align grey-text">
                    <p>Publié le {{ event.publicationDate|date('j F Y') }}</p>
                </div>
                <div class="flow-text purple-text">
                    {{ event.eventDate|date('j F Y') }}
                </div>
                <div class="row">
                    <div class="col s12 l7">
                        {{ event.information }}
                    </div>
                    <div class="col s12 l5">
                        <img src="{{ asset('build/images/' ~ affichePath) }}" width="100%" class="materialboxed" alt="Logo évènement">
                    </div>
                </div>

                {% if app.user and app.user.roles.0 in ['admin', 'Owner'] %}
                    <div class="card-action">
                        <div class="row">
                            <div class="col s12 m4 center">
                                <a href="{{ path('event_index') }}">
                                    <button class="btn grey">
                                        Liste des évènements
                                        <i class="material-icons left">arrow_back</i>
                                    </button>
                                </a>
                            </div>
                            <div class="col s12 m4 center"><a class="btn"
                                                              href="{{ path('event_edit', {'id': event.id}) }}">Modifier</a>
                            </div>
                            <div class="col s12 m4 center">
                                {{ include('event/_delete_form.html.twig') }}
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% block scripts %}
        <script>$('.materialboxed').materialbox();</script>
    {% endblock %}
{% endblock %}